set(CHARM_DIR "/home/anant/winter2024/lbp/study/charm/netlrts-linux-x86_64/")
set(BASE_DIR "/home/anant/sem7/LibCharmtyles")
set(EIGEN_DIR "/usr/include/eigen3")
set(CUDA_DIR  "/path/to/CUDA/directory")
set(KOKKOS_DIR "${BASE_DIR}/kokkos/install")
set(KOKKOS_KERNELS_DIR "${BASE_DIR}/kokkos-kernels/install")

set(CHARMC "${CHARM_DIR}/bin/charmc")
set(CPU_OPTS "-c++-option -std=c++20 -O3 -march=native -DNDEBUG")
set(GPU_OPTS "-std=c++20 -O3 -march=native -DNDEBUG")
set(GPU_LINK_OPTS -O3 -language charm++ -L${KOKKOS_DIR}/lib64 -L/u/ajain18/kokkos_kernels_install/lib64 -lkokkoscore -lkokkoscontainers -lkokkoskernels -L${CUDA_DIR} -lcuda -lcudart -lcusparse -lcublas)
set(LD_OPTS "")
set(INCS "-I${BASE_DIR}")
