set(CHARM_DIR "/u/ajain18/charm/netlrts-linux-x86_64-cuda/")
set(BASE_DIR "/u/ajain18/belobench/test/LibCharmtyles")
set(EIGEN_DIR "/u/ajain18/eigen0/install")
set(CUDA_DIR  "/opt/nvidia/hpc_sdk/Linux_x86_64/25.3/cuda/12.8")
set(CUDA_MATH_LIB "/opt/nvidia/hpc_sdk/Linux_x86_64/25.3/math_libs/12.8/lib64/")
set(KOKKOS_DIR "/u/ajain18/belobench/LibCharmtyles/kokkos/install")
set(KOKKOS_KERNELS_DIR "/u/ajain18/belobench/LibCharmtyles/kokkos-kernels/install")

set(CHARMC "${CHARM_DIR}/bin/charmc")
set(CPU_OPTS "-c++-option -std=c++20 -O3 -march=native -DNDEBUG")
set(GPU_OPTS "-std=c++20 -O3 -march=native -DNDEBUG")
set(GPU_LINK_OPTS -O3 -language charm++ -L${CUDA_DIR} -L${CUDA_MATH_LIB} -lcuda -lcudart -lcusparse -lcublas -L${KOKKOS_DIR}/lib64 -L${KOKKOS_KERNELS_DIR}/lib64 -lkokkoscore -lkokkoscontainers -lkokkosalgorithms -lkokkossimd -lkokkoskernels)
set(LD_OPTS "")
set(INCS "-I${BASE_DIR}")